### ISSUE TITLE
Nonterminating Statix analysis

### ISSUE THREAD

**Issue by MeAmAnUsername** [MeAmAnUsername/pie#159]
There are a few tests in `data_def_generics.spt` for which the Statix analysis did not terminate.
~It is unclear if that is caused by unbound recursion in the Statix spec or a bug in the Statix solver.~

1. ~It might have been fixed by changes to the Statix spec since the tests were made, test that first.~
2. ~If not, figure out if it is unbounded recursion. If so, solve that, if not, file a bug report in the Statix repo.~

Definitely a Statix bug, see comment below.

**Todo**
- [ ] Open issue in NaBL repo
- [ ] Create a minimal example
- [ ] Wait for Statix bug to be fixed
- [ ] Check if it is resolved by uncommenting test expectations

**Slack threads**
Slack thread on initial problem: https://slde.slack.com/archives/C7254SF60/p1622732843164100
Attempt at fixing it: https://slde.slack.com/archives/C7254SF60/p1648242294599569

**Comment by MeAmAnUsername** [comment]
Definitely a Statix bug. See [this slack thread](https://slde.slack.com/archives/C7254SF60/p1648242294599569).
Currently not working on this yet due to time constraints.

**Comment by MeAmAnUsername** [comment]
Another example:
```
data Enum[E <: Enum[E]] = foreign java aksjdh {}
data Iterable[T] = foreign java aksdhj {}
data Collection[E] <: Iterable[E] = foreign java aksjdh {}
data BaseCollectionView[E, C <: Collection[_ <: E]] <: Iterable[E] = foreign java aksjdh {}
// analysis does not terminate if next line is included
data EnumSetView[E <: Enum[E]] <: BaseCollectionView[E, EnumSet[_ <: E]] = foreign java aksjdh {}
```
