### ISSUE TITLE
Check cascading errors

### ISSUE THREAD

**Issue by MeAmAnUsername** [MeAmAnUsername/pie#179]
Aron made a change in the nightly that should prevent cascading errors.
Test if this change works for PIE:
- [ ] #123 - Cascading errors because subexpression is incorrect: `(true + false) || true`. Expect 1 error on `true + false`.
- [ ] Multiple non-cascading errors: `2 + (/3 + 5)`. Expect 2 errors on `5` and `(/3 + 5)`. Should there be multiple errors?
- [ ] #146 - Cascading errors on call arguments when type arguments are incorrect: `id<>(3)`. Expect 1 error on `<>`.
- [ ] #139 - Non-cascading errors on call arguments when type argument is not relevant for argument: `func foo<T>(int) -> T; foo<>("8")`. Expect two errors on `<>` and `"8"`.
- [ ] #139 - Non-cascading errors on call arguments when invalid type argument is not relevant for argument: `func bar<N : int, T>(i: N, t: T); bar<string, bool>("4", "true")`. Expect 2 errors on `string` and `"true"`

**Comment by MeAmAnUsername** [comment]
Note: often does not work right now because non-resolving types return an empty data scope instead of a type variable that failed to resolve
