### ISSUE TITLE
`prefer` on `pattern` and `extension` keywords is not required?

### ISSUE THREAD

**Issue by MeAmAnUsername** [MeAmAnUsername/pie#212]
**Short description**
The `{prefer}` on the `pattern` and `extension` keywords in `syntax/func_body.sdf3` might not be required.
Check to see if it is required, remove it if not.

**Reason**
`{prefer}` is deprecated, so used of it should be removed.

**Details**
There is a comment that says "Prefer over pattern to avoid additional s from being used for something else," but I think that this may already be disallowed by follow restrictions in the template options (`template options keywords -/- ...`)

**todo**
- [ ] Remove the `{prefer}` if it is not required
- [ ] Add a test to check that `pattern` is rejected if it is followed by an `s`
- [ ] Add a test to check that `extension` is rejected if it is followed by an `s`

**related issues**
- This solves a part of #132
