### ISSUE TITLE
More permissive parsing of foreign java functions/tasks/constructors

### ISSUE THREAD

**Issue by MeAmAnUsername** [MeAmAnUsername/pie#215]
**Short description**
Allow parsing of foreign java tasks, methods and constructors when it misses / has a superfluous method name.

**Todo**
- [ ] Allow parsing a method in foreign tasks: `foreign Foo#not_allowed`
- [ ] Allow parsing a missing method in foreign methods: `foreign java Foo`
- [ ] Allow parsing a method in foreign Java constructors: `foreign java constructor Foo#not_allowed`

**Example**
Code: `foreign java constructor Foo#bar`
Current behavior: fails to parse entirely with error 'Unexpected input'
Proposed behavior: parse, show error "Java constructors cannot have a method name. Remove the method name 'bar' to refer to a constructor of 'Foo' or remove the keyword 'constructor' to refer to the method 'bar'" on `#bar`

**Reason**
When it fails to parse right now, it does not show a proper error with reason why it fails. From experience, it is quite common to forget to add/remove the method name.

**Implementation**
SDF3 has a [recovery keyword](https://www.spoofax.dev/references/syntax/recovery/). This allows it to parse, but I don't know how to customize the error message.
