### ISSUE TITLE
Give warnings for unobserved functions

### ISSUE THREAD

**Issue by MeAmAnUsername** [MeAmAnUsername/pie#218]
**Summary**
Show warnings for functions that are unused. There is no way for the static analysis to know which functions are explicitly observed at runtime, so it requires that the user lists functions that are explicitly observed in a config file.

**Todo**
- [ ] Configuration files
   - [ ] Determine how to read external file into Statix.
   - [ ] Choose a file format
   - [ ] Implement reading configuration files and marking explicitly observed tasks
- [ ] Implement keeping track of which functions are used
- [ ] Testing
   - [ ] Determine how to test this
   - [ ] Write tests
- [ ] Documentation
   - [ ] Write reference documentation
   - [ ] Write How-to: How to show unused tasks
- [ ] Decide which of the extensions/future work is worthwhile to turn into its own issue.

**Detailed problem description**
It would be useful to show warnings on functions that are unused (unobserved), as this allows removing those unused functions or may remind users to use the function.
It is impossible to know which functions are observed purely from static analysis, because the PIE DSL code does not have a set entry function like `main` in C and Java.
Instead, either the user needs to mark functions as observed, or there has to be an automated way to extract that information.

**Proposed solution**
Mark tasks as explicitly observed in a configuration file, every other task is considered not explicitly observed. Every observed tasks makes the tasks that it depends on observed too. There is a warning for every unobserved task within the main project, where 'main project' means source code for the current project, not imported projects. Warnings are only shown in the main project because imported projects may provide tasks that the current project does not need, but that should not result in a warning.
This feature can (and should?) be made optional, i.e. all of this only happens if at least one task is marked as explicitly observed.

The warning is shown on the name of the function at its declaration.
The configuration file format should allow combining multiple configuration files. That would allow having some files with observed tasks generated by tools, and one manual file with added observed tasks. The format could be as simple as a file named `*.observed` with tasks on separate lines (possibly with support for comments), but should probably be a more normal file format such as JSON, YAML, `*.properties` or maybe `*.cfg`

**Alternative solutions**
Another option that was considered is to annotate functions in-file as (un)observed. This was rejected because it does not apply to shared code: maybe the original project `A` observes a task, but a project `B` that imports `A` does not observe that task.
For example, a library would like every task to be considered observed (i.e. every task could potentially be used by a user of the library), but if you use the library you want every task to be considered unobserved.

**Extensions / future work**
Not all of these are good ideas, but they should be considered. When this issue is resolved, decide which of these are good enough to turn into new issues.
1. Make only giving warnings in the main project configurable, i.e. give the option to _do_ show warnings for unobserved tasks in imported projects, although I don't see any plausible use case right now. Maybe 'show/don't show warnings for imported projects' should just be an option in general?
2. Generate configuration for the observed tasks of a project. Examples:
   - Spoofax 3 can mark tasks for commands as observed.
   - Downstream projects can automatically generate a list of observed tasks for imported projects. These can then be used by the upstream project to know which tasks are used. 
   For example, given projects `A`, `B` and `C`, where `B` and `C` import `A`, `B` and `C` can generate a file with the tasks they observe. Project `A` can then use these generated config files to know which tasks are observed. It can also explicitly observe certain tasks to kind of mark them as the 'public interface' of the project.
3. Consider explicitly observed tasks as the public interface of a project, and include only these tasks in generated documentation for the project.
4. Do not generate code for unobserved tasks (also in imported projects) unless explicitly set to generate code for unused tasks with compiler flag.
5. Some way to import explicitly observed tasks from a project. Not as easy as it may seem: AFAIK it is the exporting project that  decides whether to export something, not the importing project that can decide whether to import something.

**Related issues**
- For ways to check whether an element is used, see #203
- Only generate documentation for explicitly observed tasks: #56
