### ISSUE TITLE
Write e2e tests for foreign Java functions

### ISSUE THREAD

**Issue by MeAmAnUsername** [MeAmAnUsername/pie#222]
**Summary**
Write e2e tests for calling foreign Java functions (`func ... = foreign java ...`)

**Todo**
- [x] add test with 0 parameters
- [x] add test with 1 parameter
- [x] add test with 2 parameters
- [x] add test with 3 parameters
- [x] add test with with type arguments (requires #24) or add as todo for #24

**Reason**
Code generation for calling foreign Java functions is currently not tested explicitly (just as side effects of testing other things), and completely untested for more than 1 parameter. It should be tested to prevent regressions and to add confidence when changing the code generation

**Implementation**
Create a directory `lang/lang.test/src/test/java/mb/pie/lang/test/call/foreignFunction` to implement the tests

**Related issues**
- Proposal to rename the directory where these tests should be added [done]: #221
- Test with type arguments requires that #24 has been merged
- Similar issue for foreign tasks: #223

**Comment by MeAmAnUsername** [comment]
Directory was renamed (see #221), updated issue description

**Comment by MeAmAnUsername** [comment]
Implemented in pie-dsl-issue-24-generics-statix, will be merged with #24
