### ISSUE TITLE
Write e2e tests for foreign tasks

### ISSUE THREAD

**Issue by MeAmAnUsername** [MeAmAnUsername/pie#223]
**Summary**
Write e2e tests for calling foreign Java tasks (`func ... = foreign ...`)

**Todo**
- [x] add test with 0 parameters
- [x] add test with 1 parameter
- [x] add test with 2 parameters
- [x] add test with 3 parameters
- [x] add test with with type arguments (requires #24) or add as todo for #24

**Reason**
Code generation for calling foreign tasks is currently completely untested. It should be tested to prevent regressions and to add confidence when changing the code generation

**Implementation**
Create a directory `lang/lang.test/src/test/java/mb/pie/lang/test/call/foreignTask` to implement the tests

**Related issues**
- Proposal to rename the directory where these tests should be added: #221
- Test with type arguments requires that #24 has been merged
- Similar issue for foreign functions: #222

**Comment by MeAmAnUsername** [comment]
Directory was renamed (see #221), updated issue description

**Comment by MeAmAnUsername** [comment]
Non-type parameterized tests are done. Test with generics is also done, but discovered a bug.

**Comment by MeAmAnUsername** [comment]
Bug finally fixed, this issue is now implemented, will be merged with #24
