### ISSUE TITLE
Allow casting types

### ISSUE THREAD

**Issue by MeAmAnUsername** [MeAmAnUsername/pie#228]
**Summary**
Allow casting an expression to a specific type.
Syntax: `$Exp as $Type`

**Todo**
- [ ] Answer open questions
- [ ] Design this feature
- [ ] Implement feature
- [ ] Add tests
- [ ] Add this feature to the documentation

**Open questions**
- Is there a use case for casting?
   ~PIE type system is not perfect, so presumably there is. However, I don't have a concrete one right now.~
   Edit: can use casting to cast between two data types that have the same backing class. This includes casting built-in types, e.g. `T*` to `ArrayList<T>`. This would be a workaround for #69.
- Is it a good idea to allow casting?
- Allow casting to some type that is completely different?
Should probably be allowed, given that it is currently not possible to express multiple inheritance.
May be able to use a safe cast, which returns `null` if the cast fails. See [Safe casts﻿ in Kotlin](https://kotlinlang.org/docs/null-safety.html#safe-casts)

**Related issues**
- One of the reasons to implement casts is to support undeclared interfaces with multiple inheritance. #107 resolves this by making it possible to declare these instead.
- This could make it possible to declare methods on built-in types by declaring a datatype with that method and then casting the built-in type to the custom type. See #69.
