### ISSUE TITLE
Enable code completion

### ISSUE THREAD

**Issue by MeAmAnUsername** [MeAmAnUsername/pie#242]
**Summary**
Enable code completion.

**Todo**
- [ ] Figure out if static semantics are derived automatically
- [ ] Write static semantics if not derived automatically
- [ ] Enable code completion
   - [ ] Enable code completion suggestions with CTRL+space
   - [ ] Including semantic suggestions if possible
   - [ ] Better error messages
- [ ] Write documentation

**Example**
Given `func example() -> int = $Exp`, using CTRL+space (control+space on Mac) when the cursor is on `$Exp` should show a list of possible expressions that can be used there.
Ideally, with semantic code completions it only gives suggestions that could have type `int`, i.e. not logical and, logical or, logical negation, built-in path stuff, etc.
Additionally, there should be an error message on `$Exp` like
```
Incomplete code. Replace the placeholder with actual code.
Hint: use CTRL+space to show suggestions
```

**Reason**
Code completion could help users discover new language features, and can speed up development (particularly if you don't know the specific syntax for something)

**Details**
Spoofax has code completion with CTRL+space. There has recently also been work on adding static semantics support for it, so now might be a good time to add this to PIE DSL.

**Open questions**
- How to enable this?
- Are static semantics for completions derived automatically or do they need to be defined manually?

**Related issues**
- #243 changes the syntax for placeholders, but should not interfere with this issue. May be a good idea to implement that one together with this one.
