### ISSUE TITLE
Add templates for new issues

### ISSUE THREAD

**Issue by MeAmAnUsername** [MeAmAnUsername/pie#247]
**Summary**
Add templates for issues in PIE repo

**Todo**
- [ ] Decisions
   - [ ] Decide which issue kinds to include
   - [ ] Decide on sections for each kind
- [ ] Write templates
- [ ] Add to repo

**Reason**
This provides a standard layout for issues and ensures that all required information is included in new issues, which speeds up resolution

**Example**
This issue is an example of a feature request. #245 is an example of a bug report

**Detailed information**
Most sections are optional if they do not contain information or do not apply
Kinds of issues and proposed sections for each:
- Bug report
   - summary
   - todo: reproduce, add test, fix, update docs
   - reproduction steps: given, expected, actual
   - Known workarounds
   - additional info
   - implementation
   - related issues
   - search terms
- Feature request
   - summary
   - todo: decide on specification / answer outstanding questions, implement, add tests, update docs
   - reason
   - example: current behavior/way of doing it, proposed behavior/way of doing it
   - detailed information
   - alternative solutions
   - implementation
   - related issues
   - search terms

**Implementation**
Has to be added to master branch, so will probably need to be added to metaborg/pie, not this fork
