### ISSUE TITLE
Early exit in list operations

### ISSUE THREAD

**Issue by MeAmAnUsername** [MeAmAnUsername/pie#258]
**Summary**
Test if return and fail expressions work in list comprehensions, appending and concatenating

**Todo**
- [ ] Add tests
   - [ ] List comprehension: return
   - [ ] List comprehension: fail
   - [ ] List concatenation: return
   - [ ] List concatenation: fail
   - [ ] Append to list: return
   - [ ] Append to list: fail
- [ ] Fix (add items here for failing tests)

**Description**
Returning from a lambda is not possible in Java, so if the generated code does not keep this in mind it will break with early exits.
This likely is not tested yet

**Implementation**
As this concerns code generation, it should be tested with end-to-end tests.

**Related issues**
None
