### ISSUE TITLE
Write e2e tests for methods

### ISSUE THREAD

**Issue by MeAmAnUsername** [MeAmAnUsername/pie#261]
**Summary**
Write e2e tests for calling methods on foreign Java data types (`data ... = foreign java ... { func ... }`)

**Todo**
- [x] add test with 0 parameters
- [x] add test with 1 parameter
- [x] add test with 2 parameters
- [x] add test with 3 parameters
- [x] add test with with type arguments (requires #24) or add as todo for #24
- [x] add + fix test that replicates failing behavior in `tiger.pie` for `Result[T, E].unwrap()`
   - [x] Reproduce
   - [x] Minimize example
   - [x] Add failing test
   - [x] Fix issue
   - [x] Verify that it also solved the code generation for tiger.pie

**Reason**
Code generation for calling foreign methods is currently completely untested. It should be tested to prevent regressions and to add confidence when changing the code generation

**Implementation**
Create a directory `lang/lang.test/src/test/java/mb/pie/lang/test/call/foreignMethod` to implement the tests

**Related issues**
- Similar issue for foreign functions: #222
- Similar issue for foreign tasks: #223

**Comment by MeAmAnUsername** [comment]
Implemented in `pie-dsl-issue-24-generics-statix`, will be merged with #24
