### ISSUE TITLE
Create e2e tests for walk and list expressions

### ISSUE THREAD

**Issue by MeAmAnUsername** [MeAmAnUsername/pie#263]
**Summary**
Create end-to-end tests for `walk` and `list` expressions

**Todo**
- [x] Write tests for walk
   - [x] No filter
   - [x] regex
   - [x] pattern
   - [x] patterns
   - [x] extension
   - [x] extensions
- [x] Write tests for list
   - [x] No filter
   - [x] regex
   - [x] pattern
   - [x] patterns
   - [x] extension
   - [x] extensions
- [x] Update code generation
- [x] Check that it works in tiger.pie

**Reason**
There are currently no tests for code generation of list and walk expressions, which lead to a bug (removed desugaring while going to Statix but did not update code generation)

**Implementation**
To fix the bug: `p2j-ast-filter`, func_body.str:941-950: add `Some` around input constructors

**Related issues**
- Other issues about missing end-to-end tests: #222, #223, #261, #262

**Comment by MeAmAnUsername** [comment]
Finished in `pie-dsl-issue-24-generics-statix`, will be merged with #24
