### ISSUE TITLE
Function to create safe java class ids

### ISSUE THREAD

**Issue by MeAmAnUsername** [MeAmAnUsername/pie#276]
**Summary**
Create a function that correctly generates safe java class ids and use it everywhere.

**Todo**
- [ ] implement rules that transform to safe java class ids
  - [ ] regular names
  - [ ] dashes
  - [ ] keywords/java reserved words
  - [ ] Use type arguments for injected classes
- [ ] Use function everywhere (search for `_` and `-` to find some uses)

**Reason**
Currently does not handle keywords, and much of the logic for escaping dashes and keywords is duplicated across multiple places.

**Implementation**
There is already a strategy `pie-sanitize-class-id`, but it is not used everywhere, and only handles dashes. To handle keywords, it could add specific rules that provide specific outputs, e.g. `pie-sanitize-class-id: "super" -> "$super"` (note: check if this works with strings with annotations).
To handle type arguments, it could additionally take a list of type arguments and stringify them too.

**Related issues**
None
