### ISSUE TITLE
Give warnings when type parameters do not have multiple solutions

### ISSUE THREAD

**Issue by MeAmAnUsername** [MeAmAnUsername/pie#278]
**Summary**
Give warnings when no solutions or only one solution exists for the constraints on type parameters

**Todo**
- [ ] Figure out general rules when constraints do not have multiple solutions
   - [ ] Find more examples of places where there is only one solution
   - [ ] Minimize examples
   - [ ] Figure out general rules when constraints do not have multiple solutions
- [ ] Write tests (use minimized examples)
- [ ] Implement

**Reason**
Using type parameters is useless if there is only one possible instantiation, so it should give a warning when detected.

**Examples**
```
// don't know for sure if this is an example, but I think it is
data Fruit[A <: Fruit[B, A], B :> Fruit[B, A]] = foreign java Fruit {}
```
