### ISSUE TITLE
Add list with explanations of editor messages

### ISSUE THREAD

**Issue by MeAmAnUsername** [MeAmAnUsername/pie#281]
**Summary**
Add a list with explanations for errors, warnings and notes to the documentation

**Todo**
- [ ] Get list of all errors, warnings and notes
- [ ] Consolidate/merge messages where practical
- [ ] Create file, add to TOC
- [ ] Write list

**Reason**
While most errors, warnings and notes should be self explanatory, they often do not exhaustively explain everything, so it would be nice to have such an explanation in the documentation

**Description**
Messages can be consolidated/merged when practical. I expect that many `Type mismatch` messages can be merged.
Each message should explain what it means, the cause, and how to solve it.
Also explain what `BUG:` and `BUG?:` messages mean: a fundamental assumption of the DSL static semantics spec turns out to not be true, so it is (or for `BUG?`, might be) a bug in the spec. Please file a bug report.

**Related issues**
None
