### ISSUE TITLE
Useful link with explanation of subtyping in Kotlin?

### ISSUE THREAD

**Issue by MeAmAnUsername** [MeAmAnUsername/pie#283]
**Todo**
- [ ] Decide where to put link
- [ ] Link to this blog post: http://www.natpryce.com/articles/000818.html
- [ ] Describe differences with PIE
   - [ ] PIE top type is nullable, while Kotlin `any` type is not
   - [ ] more...?

**Location**
Explanation of subtyping should be clear enough on its own (that is to say, the intention is that the documentation on subtyping in the PIE DSL is clear enough, I don't know if it is at the moment), but maybe a note like "parallels with subtyping in Kotlin" might help, or mention it in background somewhere.
